### ISSUE TITLE
Demo rendering issue

### ISSUE THREAD

**Issue by YouGuessedMyName** [sjunges/gridworld-by-storm#3]
If I run the demo.py file, I get a video where the green block stays stuck in the bottom right of the frame. I think it's supposed to move?
![image](https://github.com/user-attachments/assets/71877df6-8f9d-444a-a11f-78e801eccda3)

**Comment by sjunges** [comment]
Indeed, something is broken, likely due to a new version of storm or matplotlib. I will investigate.

**Comment by sjunges** [comment]
Thanks for the bug report, it should be fixed.
